# Generated by Django 3.2 on 2021-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('Choice_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice', models.CharField(max_length=50)),
                ('Icon', models.CharField(max_length=60)),
                ('Question_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('Question_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('User_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=20)),
                ('User_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('Word_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word_th', models.CharField(max_length=100)),
                ('Sound', models.CharField(max_length=100)),
            ],
        ),
    ]
